data <- read.csv2("household_power_consumption.txt",stringsAsFactors = FALSE)
data1 <- data[data$Date == "1/2/2007" | data$Date == "2/2/2007", ]
data2 <- data.frame(Newtime = (1:2880)/1440 , data1)
plot(data2$Newtime,data2$Sub_metering_1,type = "l",ylab = "Global Active Power", xlab="", axes=FALSE)
lines(data2$Newtime,data2$Sub_metering_2, type="l",col = "red")
lines(data2$Newtime,data2$Sub_metering_3, type="l",col = "blue")
axis(1, at=0:2, lab=c("Thu","Fri","Sat"))
axis(2)
box()
legend("topright",legend <- c("Sub_metering1","Sub_metering2","Sub_metering3"), col=c("black","red","blue"),lwd=1)
dev.copy(png, file ="plot3.png",width = 480, height = 480)
dev.off()
